config/routes.rb
Rails.application.routes.draw do
 get 'homes/top'
  get 'homes/about'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' , to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  validates :body, length: { maximum: 200 }

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true

  validates :name, uniqueness: true

  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }

  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @book_new = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book_new.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    Book.find_by(id: params[:id]).destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @book_new = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @books = Book.all
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have created user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<h2>User info</h2>
        <table class='table'>
          <tr>
            <th><%= image_tag user.get_profile_image, size: "100x100" %></th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>

        </table>
        <div class='row'>
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

app/views/books/_books2.html.erb
<h2 class="mt-3">New book</h2>
        <%= form_with model: book_new, local:true do |f| %>
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %></br>
          <%= f.submit 'Update Book' %>
        <% end %>

        <%= link_to "Show", book_path %>
　　　　 |
　　　　<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<main>
  <% if @book_new.errors.any? %>
    <%= @book_new.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @book_new.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <%= render 'books', user: @user %>
        <%= render 'books2', book_new: @book_new %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
         <% @books.each do |book| %>
           <td>
             <%= link_to user_path(book.user) do %>
              <td><%= image_tag book.user.get_profile_image, size: "100x100" %></td>
              <td><%= link_to book.title, book_path(book) %></td>
             <% end %>
           </td>
               <th><%= book.body %></th>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <%= render 'books', user: @user %>
        <%= render 'books2', book_new: @book_new %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>
        <table class='table table-hover table-inverse'>

          <tbody>
            <tr>
             <td>
              <%= link_to user_path(@user.id) do %>
               <%= image_tag @user.get_profile_image, size: "100x100" %><br/>
               <%= @user.name %>
              <% end %>
             </td>
             <td>
              <%= link_to book_path(@book.id) do %>
               <%= @book.title %>
              <% end %>
             </td>
             <td>
               <%= @book.body %>
             </td>
               <% if @user == current_user %>
             <td>
               <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
             </td>
             <td>
               <%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "削除しますか？" %>
             </td>
             <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <!-- ログイン後のHomeリンクは未実装です。自分で調べて実装してみましょう -->
             <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
                Home
             <% end %>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fa-solid fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
              <i class="fa-solid fa-book-open"></i>Books
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fa-solid fa-right-from-bracket"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fa-solid fa-house"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fa-solid fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fa-solid fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fa-solid fa-right-to-bracket"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/7962587c58.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></p>
  <label>Introduction</label>
  <P><%= f.text_area :introduction %></P>
  <label for="inputImage">Image</label>
  <P><%= f.file_field :profile_image, accept: "image/*" %></P>
  <P><%= f.submit "Update User" %></P>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>

        <table class='table'>
          <tr>
            <th>
              <%= image_tag @user.get_profile_image, size: "100x100" %>
            </th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>

        </table>
        <div class='row'>

          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>

        <%= form_with model: @book_new, local:true do |f| %>
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
         <% @users.each do |user| %>
           <tr>
              <td><%= image_tag user.get_profile_image, size: "100x100" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
           </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <table class='table'>
          <tr>
            <th><%= image_tag @user.get_profile_image, size: "100x100" %></th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>

        </table>
        <div class='row'>
          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
         <% @books.each do |book| %>
           <td>
             <%= link_to user_path(@user.id) do %>
              <td><%= image_tag @user.get_profile_image, size: "100x100" %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
             <% end %>
           </td>
              <th><%= book.body %></th>
           </td>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>